package adventuria

const (
	TableUsers      = "users"
	TableActions    = "actions"
	TableCells      = "cells"
	TableItems      = "items"
	TableInventory  = "inventory"
	TableWheelItems = "wheel_items"
	TableLogs       = "logs"
	TableTimers     = "timers"

	ActionTypeRoll          = "roll"
	ActionTypeReroll        = "reroll"
	ActionTypeDrop          = "drop"
	ActionTypeDone          = "done"
	ActionTypeGame          = "game"
	ActionTypeRollCell      = "rollCell"
	ActionTypeRollPreset    = "rollPreset"
	ActionTypeRollMovie     = "rollMovie"
	ActionTypeRollItem      = "rollItem"
	ActionTypeRollBigWin    = "rollBigWin"
	ActionTypeRollDeveloper = "rollDeveloper"
	ActionTypeMovieResult   = "movieResult"

	CellTypeGame      = "game"
	CellTypeStart     = "start"
	CellTypeJail      = "jail"
	CellTypeBigWin    = "big-win"
	CellTypePreset    = "preset"
	CellTypeMovie     = "movie"
	CellTypeItem      = "item"
	CellTypeDeveloper = "developer"

	UserNextStepRoll             = "roll"
	UserNextStepChooseResult     = "chooseResult"
	UserNextStepChooseGame       = "chooseGame"
	UserNextStepRollJailCell     = "rollJailCell"
	UserNextStepRollBigWin       = "rollBigWin"
	UserNextStepRollOnBigWinDrop = "rollOnBigWinDrop"
	UserNextStepRollPreset       = "rollPreset"
	UserNextStepRollMovie        = "rollMovie"
	UserNextStepMovieResult      = "movieResult"
	UserNextStepRollItem         = "rollItem"
	UserNextStepRollDeveloper    = "rollDeveloper"

	LogTypeItemUse  = "itemUse"
	LogTypeItemDrop = "itemDrop"
)
